### ISSUE TITLE
libpthread not found - (compiling)

### ISSUE THREAD

**Issue by oceanpix** [Gundersanne/portaudio_opensles#2]
Hi! I'm trying to compile the library with "crosscompile_portaudio_android.sh" that you uploaded in the pa-android-tests-master repository.
On Ubuntu 16.04 (tested on both 32/64 bit) I created the toolchain from the suggested NDK versions r9b with -api 14, but the compilation fails with this message:

checking for pthread_create in -lpthread... no
configure: error: libpthread not found!
make: *** No rule to make target 'install'.  Stop.

Are there packages that need to be installed other than the NDK? Thanks!

**Comment by Gundersanne** [comment]
Hai,

Not at all. Pthread is built into the NDK and you don't need to explicitly link it, so it's in there.

Be sure to checkout the portaudio_opensles_ticket_154 branch and not the master branch!

Also best to do another pull first, because I just noticed I didn't push a bug fix in pa_startstream.

So git pull, git checkout portaudio_opensles_ticket_154, and then run the script again.

**Comment by oceanpix** [comment]
Hi Gundersanne! Thank you very much for your answer, I was able to download the git from the ticket 154 and successfully compile and run portaudio on Android! This is really great, thank you really much!! :)

**Comment by Gundersanne** [comment]
You're very welcome! Thanks for using it :)
